### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by nyvelius** [bbc/brave#78]
Hi

I thought I would investigate this project for live streaming. So far I've unfortunately gotten stuck on starting it.

**System**
macOS Big Sur 11.2.1

**Steps to reproduce**
```
git@github.com:bbc/brave.git
pip3 install --user pipenv
pipenv install
brew install libffi
(added to .bash_profile) export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
brew install libnice openssl librsvg libvpx srtp
brew install gstreamer
brew install gst-plugins-base
brew install gst-plugins-good
brew install gst-plugins-bad
brew install gst-plugins-ugly
brew install gst-libav gst-python
pipenv run python3 brave.py
```
**Result**
```
Error processing line 1 of /Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/ruamel.yaml-0.16.10-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "<frozen importlib._bootstrap_external>", line 1281, in _path_importer_cache
  KeyError: 'VextFinder.PATH_TRIGGER'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap_external>", line 1189, in __contains__
    File "<frozen importlib._bootstrap_external>", line 1164, in _recalculate
    File "<frozen importlib._bootstrap_external>", line 1311, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1283, in _path_importer_cache
    File "<frozen importlib._bootstrap_external>", line 1259, in _path_hooks
    File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
      sitedir = getsyssitepackages()
    File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
      output = run()
    File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 42, in call_f
      output = subprocess.check_output(cmd, env=env).decode('utf-8')
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1583, in _execute_child
      and os.path.dirname(executable)
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 152, in dirname
      p = os.fspath(p)
  TypeError: expected str, bytes or os.PathLike object, not NoneType

Remainder of file ignored
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Failed checking if argv[0] is an import path entry
Traceback (most recent call last):
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1281, in _path_importer_cache
KeyError: 'VextFinder.PATH_TRIGGER'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "brave.py", line 10, in <module>
    import brave.session
  File "/Users/testuser/dev/experiment/brave/brave/session.py", line 6, in <module>
    from brave.helpers import get_logger
  File "/Users/testuser/dev/experiment/brave/brave/helpers.py", line 3, in <module>
    import gi
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1311, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1283, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1259, in _path_hooks
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/gatekeeper/__init__.py", line 227, in __init__
    sitedir = getsyssitepackages()
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 99, in getsyssitepackages
    output = run()
  File "/Users/testuser/.local/share/virtualenvs/brave-rDStWLUb/lib/python3.8/site-packages/vext/env/__init__.py", line 42, in call_f
    output = subprocess.check_output(cmd, env=env).decode('utf-8')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1583, in _execute_child
    and os.path.dirname(executable)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by moschopsuk** [comment]
At the moment i do not have a Big Sur install so i am unable to reproduce, it may be worth using the dockerfile to build and run inside a container.

**Comment by opn** [comment]
Would be great to update the instructions for BigSur - spent several hours yesterday trying to install and it's tricky. 

```
pipenv run python3 brave.py
```
results in

```
Traceback (most recent call last):
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave.py", line 10, in <module>
    import brave.session
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave/session.py", line 5, in <module>
    import brave.config_file
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave/config_file.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

I tried several ways of upgrading to python3 - so I can either import or link `pip` - or should that be `pip3'

```
pip3 install pyyaml
```

installs successfully but does not fix the issue. Recommends I try:

```
/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip
```

which upgrades pip. But then I get:

```
🍺  /usr/local/Cellar/gst-plugins-bad/1.18.4: 264 files, 20.8MB, built in 2 minutes 17 seconds
fortyfoxes@Black-5 brave % pipenv run python3 brave.py                       
Traceback (most recent call last):
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave.py", line 10, in <module>
    import brave.session
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave/session.py", line 6, in <module>
    from brave.helpers import get_logger
  File "/Users/fortyfoxes/Documents/git-repos/PlatformEarth/brave/brave/helpers.py", line 3, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

I try installing `pip3 install vext` and `pip3 install vext.gi` but it does not help. 

I give up.... awaiting updates here for Big Sur
