### ISSUE TITLE
Unable to add element intervideosink

### ISSUE THREAD

**Issue by brucekim** [bbc/brave#81]
Hi there,

I have built the latest source of brave and performed simple test, 
* installed: GStreamer 1.14.3, python3.6 and all other preliminaries including libraries.
* simple test pipeline: a video input -> mixer -> output(rtmp)

However it doesn't work at adding input to mixer.
I think 'intersink' has not been created properly.

Does anyone know how t solve it?

debug log
--------
[2021-03-25 13:01:29 +0900] [45497] [INFO] Goin' Fast @ http://0.0.0.0:5000
    INFO: [   output1] RTMP output now configured to send to rtmp://[test_rtmpserver_ip_addr]/live/livestream
   ERROR: [    input1] Unable to add element intervideosink
   ERROR: [    input1] Unable to add element queue
Traceback (most recent call last):
  File "brave.py", line 71, in <module>
    start_brave()
  File "brave.py", line 61, in start_brave
    session.start()
  File "/home/bkim/git/brave/brave/session.py", line 36, in start
    self._setup_initial_inputs_outputs_mixers_and_overlays()
  File "/home/bkim/git/brave/brave/session.py", line 89, in _setup_initial_inputs_outputs_mixers_and_overlays
    mixer.setup_sources()
  File "/home/bkim/git/brave/brave/mixers/mixer.py", line 94, in setup_sources
    connection.add_to_mix(details)
  File "/home/bkim/git/brave/brave/connections/connection_to_mixer.py", line 47, in add_to_mix
    self._ensure_elements_are_created()
  File "/home/bkim/git/brave/brave/connections/connection_to_mixer.py", line 186, in _ensure_elements_are_created
    self._create_video_elements()
  File "/home/bkim/git/brave/brave/connections/connection_to_mixer.py", line 212, in _create_video_elements
    intervideosrc, intervideosink = self._create_inter_elements('video')
  File "/home/bkim/git/brave/brave/connections/connection.py", line 99, in _create_inter_elements
    intersink.set_property('channel', channel_name)
AttributeError: 'NoneType' object has no attribute 'set_property'

yaml configuration
--------
enable_video: true
enable_audio: true

default_mixer_width: 640
default_mixer_height: 360

inputs:
     - id: 1
       type: test_video
       pattern: 18

outputs:
     - type: rtmp
       uri: rtmp://[test_rtmpserver_ip_addr]/live/livestream
       source: mixer1

mixers:
     - sources:
         - uid: input1
           zorder: 2
           width: 160
           height: 90

**Comment by brucekim** [comment]
This has been resolved with reinstalling latest gstreamer, 1.19.0,  on Ubuntu 20.04.
